config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "scans#index"
  resources :comparisons, only: %i[create show] do
    member do
      get 'csv', to: 'comparisons/csv#show'
    end
  end
  resources :scans, only: %i[index create]
end

app/models/application_record.rb
# frozen_string_literal: true

# Base-level model for others to inheret from
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comparison.rb
# frozen_string_literal: true

require 'csv'

# Records a comparison between a warehouse scan and the expected manifest
class Comparison < ApplicationRecord
  belongs_to :scan

  def processing?
    comparison_outcome.nil?
  end

  def self.create_from_manifest(scan:, manifest_file:)
    manifest_contents = File.read(manifest_file)
    expected_manifest = CSV.parse(manifest_contents)
    Comparison.create!(scan:, expected_manifest:)
  end

  def headers
    return [] if comparison_outcome.nil?

    comparison_outcome.first
  end

  def outcome_data
    return [] if comparison_outcome.nil?

    comparison_outcome[1..]
  end
end

app/models/scan.rb
# frozen_string_literal: true

# The results of a single database scan performed by a warehouse robot
class Scan < ApplicationRecord
  has_one :comparison, dependent: :destroy

  def self.create_from_json(report_file:)
    file_contents = File.read(report_file)
    report_contents = JSON.parse(file_contents)

    create!(report_contents:)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comparisons/csv_controller.rb
# frozen_string_literal: true

module Comparisons
  # Handles requests for CSV downloads of comparison reports
  class CsvController < ApplicationController
    def show
      @comparison = Comparison.find(params[:id])
      headers = @comparison.headers
      outcome = @comparison.comparison_outcome[1..]

      # This could also be moved into a service object or class method on Comparison in future
      csv_data = CSV.generate(headers: true) do |csv|
        csv << headers
        outcome.each do |row|
          csv << row
        end
      end

      send_data csv_data, filename: "comparison_#{params[:id]}.csv", type: 'text/csv'
    end
  end
end

app/controllers/comparisons_controller.rb
# frozen_string_literal: true

# Handles requests for pending and completed comparison reports.
class ComparisonsController < ApplicationController
  before_action :validate_request, only: %i[create]
  before_action :set_scan, only: %i[create]

  def create
    @comparison = Comparison.create_from_manifest(scan: @scan, manifest_file: params[:manifest])
    CalculateComparisonReportJob.perform_later(@comparison)

    render turbo_stream: [
      turbo_stream.append('verified-scans-table', partial: 'scans/verified_scan_row', locals: { scan: @scan }),
      turbo_stream.remove("unverified-scan-row-#{@scan.id}")
    ]
  rescue StandardError => e
    redirect_to scans_path, alert: e.message
  end

  def show
    @comparison = Comparison.includes(:scan).find(params[:id])
    @headers = @comparison.headers
    @outcome = @comparison.outcome_data
  end

  private

  def validate_request
    return if params[:manifest].present?

    redirect_to scans_path, alert: 'Please attach a manifest for comparison!'
  end

  def set_scan
    @scan = Scan.find(params[:scan_id])
  end

  def comparison_params
    params.permit(:manifest, :scan_id)
  end
end

app/controllers/scans_controller.rb
# frozen_string_literal: true

# Incoming scan data from Robot warehouse scanners
class ScansController < ApplicationController
  before_action :set_scans, only: %i[index]

  def index; end

  def create
    Scan.create_from_json(report_file: scan_params['file'])
    head :created
  rescue JSON::ParserError => e
    render status: :bad_request, json: { errors: e.message }
  end

  private

  def set_scans
    @scans = Scan.all.includes(:comparison).order(created_at: :desc)
    @verified_scans = @scans.where.not(comparison: { scan_id: nil })
    @unverified_scans = @scans.where(comparison: { scan_id: nil })
  end

  def scan_params
    params.require(:scan).permit(:file)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Base-level helper for others to inheret from
module ApplicationHelper
end

app/views/comparisons/show.html.erb
<h1>Warehouse Comparison Report</h1>

<div><%= link_to 'Back to Index', scans_path %></div>

<p>To export this report as a CSV file, please click here:
    <%= link_to 'Export as CSV', csv_comparison_path(@comparison) %>
</p>

<table>
    <tr>
        <% @headers.each do |header|%>
            <th><%= header %></th>
        <% end %>
    </tr>
    <% @outcome.each do |row| %>
        <tr>
            <% row.each do |cell| %>
                <td><%= cell %></td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/csv/index.html.erb
<h1>Csv#index</h1>
<p>Find me in app/views/csv/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DexoryWarehouseScan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if alert.present? %>
      <div class="alert">
        <%= "ERROR: " + alert %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/scans/_unverified_scans.html.erb
    <p>To validate the results of a scan, please upload a warehouse manifest file, and select a scan to compare it to.</p>    
    <table>
        <tr>
            <th>Scan ID</th>
            <th>Created At</th>
            <th colspan="2">Compare With Manifest</th>
        </tr>
        <% scans.each do |scan| %>
            <%= form_tag({controller: 'comparisons', action: 'create'}, method: 'post', multipart: true) do %>
                <%= hidden_field_tag :scan_id, scan.id %>
                <tr id='<%= "unverified-scan-row-#{scan.id}" %>'>
                    <td><%= scan.id %></td>
                    <td><%= scan.created_at %></td>
                    <td>
                        <%= file_field_tag 'manifest' %> </td>
                    <td>
                        <%= submit_tag 'Compare' %>
                    </td>
                </tr>
            <% end %>
        <% end %>
    </table>

app/views/scans/_verified_scan_row.html.erb
<tr id='<%= "verified-scan-row-#{scan.id}" %>'>
    <td><%= scan.id %></td>
    <td><%= scan.created_at %></td>
    <td>
        <% if scan.comparison.processing? %>
            <div>Report is generating, please wait...</div>
        <% else %>
            <a href="<%= comparison_path(scan.comparison) %>">See Comparison Report</a>
        <% end %>
    </td>
</tr>

app/views/scans/_verified_scans.html.erb
<%= turbo_stream_from "comparisons" %>
<table id='verified-scans-table'>
    <thead>
        <tr>
            <th>Scan ID</th>
            <th>Created At</th>
            <th>Results</th>
        </tr>
    </thead>
    <tbody>
        <% scans.each do |scan| %>
            <%= render partial: 'verified_scan_row', locals: { scan: scan } %> 
        <% end %>
    </tbody>
</table>

app/views/scans/index.html.erb
<h1>Warehouse Scans</h1>

<% if @scans.blank? %>
    <h2>No scans found</h2>
<% else %>
    <h2>Unverified Scans</h2>
    <% if @unverified_scans.present? %>
        <%= render partial: 'unverified_scans', locals: { scans: @unverified_scans } %>
    <% else %>
        <h3>No unverified scans found</h3>
    <% end %>
    
    <h2>Verified Scans</h2>
    <% if @verified_scans.present? %>
        <%= render partial: 'verified_scans', locals: { scans: @verified_scans } %>
    <% else %>
        <h3>No verified scans found</h3>
    <% end %>
<% end %>